import Head from 'next/head'
import HomeContainer from '@/components/Home'


export default function Home({ countries }) {
    return (
        <>
            <Head>
                <title>alibaba-rest-countries.</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeContainer {...{ countries }} />
        </>
    )
}


export async function getServerSideProps() {

    const res = await fetch(`https://restcountries.com/v3.1/all`)
    const data = await res?.json()
    return {
        props: {
            countries: data
        }, // will be passed to the page component as props
    }
}
